name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: chmod permission
      run: chmod +x ./MyDotaBuff/gradlew
    - name: Build with Gradle
      run: ./MyDotaBuff/gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: /home/runner/work/Dota2BD/MyDotaBuff/app/build/outputs/apk/xiaomi/release/app-xiaomi-release-unsigned.apk
